EMPTY = {"FRCC", "IN-DD", "IN-DN", "US-FRCC", "US-SPP", "SPP", "EEU"}
COMPATIBILITY = {
    "AUS-AC": "AU-AC",
    "Ashmore and Cartier Islands": "AU-AC",
    "AUS-ACT": "AU-ACT",
    "AUS-IOT": "AU-IOT",
    "Indian Ocean Territories": "AU-IOT",
    "AUS-NSW": "AU-NSW",
    "AUS-NTR": "AU-NT",
    "AUS-QNS": "AU-QLD",
    "AUS-SAS": "AU-SA",
    "AUS-TSM": "AU-TAS",
    "AUS-VCT": "AU-VIC",
    "AUS-WAS": "AU-WA",
    "Europe, without Russia and Turkey": "Europe, without Russia and Türkiye",
    "US-PR": "PR",
    "ASCC": "US-ASCC",
    "CSG": "CN-CSG",
    "HICC": "US-HICC",
    "MRO, US only": "US-MRO",
    "NPCC, US only": "US-NPCC",
    "RFC": "US-RFC",
    "SERC": "US-SERC",
    "TRE": "US-TRE",
    "WECC, US only": "US-WECC",
    "SGCC": "CN-SGCC",
    "IAI Area, West Europe": "IAI Area, EU27 & EFTA",
}
